<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Scry.Contracts\Scry.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Scry.Core\Scry.Core.csproj" />
    <ProjectReference Include="..\..\src\Scry.Host\Scry.Host.csproj" />
    <ProjectReference Include="..\..\src\Scry.Client\Scry.Client.csproj" />
    <ProjectReference Include="..\..\src\Scry.Analysis\Scry.Analysis.csproj" />
  </ItemGroup>

</Project>
